# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 23:20
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=65)),
                ('apellido', models.CharField(max_length=65)),
                ('mail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoUsuario', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=65)),
                ('apellido', models.CharField(max_length=65)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
