# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='codigoUsuario',
            new_name='codigo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
