# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0003_auto_20180125_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
