# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0004_auto_20180203_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=65)),
            ],
        ),
    ]
